version: '3.8'

services:
  django:
    build:
      context: ./Recommand
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Recommand:/app
    environment:
      - DJANGO_SETTINGS_MODULE=Recommand.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=1
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: